// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_XXub1amp14C5x0z6rLSt32wnIwcXXs',
    appId: '1:175870153753:web:b882b1dfded6e0c70a4688',
    messagingSenderId: '175870153753',
    projectId: 'pranav-907ab',
    authDomain: 'pranav-907ab.firebaseapp.com',
    storageBucket: 'pranav-907ab.firebasestorage.app',
    measurementId: 'G-WTSVZ1T8Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBng930LkRMwZF9jc_or-TgGrs7mR54ZdA',
    appId: '1:175870153753:android:f4e11b30be9381cc0a4688',
    messagingSenderId: '175870153753',
    projectId: 'pranav-907ab',
    storageBucket: 'pranav-907ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqiZmD9TP-TgOCyuuiD5Gt7ciDoHmXZM',
    appId: '1:175870153753:ios:799abbd41656284a0a4688',
    messagingSenderId: '175870153753',
    projectId: 'pranav-907ab',
    storageBucket: 'pranav-907ab.firebasestorage.app',
    iosBundleId: 'com.example.pranav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqiZmD9TP-TgOCyuuiD5Gt7ciDoHmXZM',
    appId: '1:175870153753:ios:799abbd41656284a0a4688',
    messagingSenderId: '175870153753',
    projectId: 'pranav-907ab',
    storageBucket: 'pranav-907ab.firebasestorage.app',
    iosBundleId: 'com.example.pranav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz_XXub1amp14C5x0z6rLSt32wnIwcXXs',
    appId: '1:175870153753:web:d7162cb0ff2e004f0a4688',
    messagingSenderId: '175870153753',
    projectId: 'pranav-907ab',
    authDomain: 'pranav-907ab.firebaseapp.com',
    storageBucket: 'pranav-907ab.firebasestorage.app',
    measurementId: 'G-7HG4MVXBB6',
  );

}